Kontroleri, servisi, login, register
RAF-SI-2022/Banka-2-Backend pull request #34
Opened 2023-03-08 19:25 UTC by DusanGligorijevic

- User controller crud operations added
-Login/Register functions added

2023-03-08 20:42 UTC, andrejanesic commented
@ntadicrn4419 da li mozes da pregledas PR? Meni deluje sve ok.

2023-03-08 20:45 UTC, andrejanesic approved these changes
Odobreno sa moje strane.

2023-03-08 20:52 UTC, ntadicrn4419 commented
> @ntadicrn4419 da li mozes da pregledas PR i dodas svoj review? Meni deluje sve ok.

Hoću

2023-03-08 20:58 UTC, andrejanesic commented
@lbrcic4219rn ovo je pr

2023-03-08 22:01 UTC, ntadicrn4419 commented on src/main/java/com/raf/si/Banka2Backend/services/UserService.java
> +    public Optional<User> findByEmail(String email) {
Metode iz ovog servisa nisu implementirane, sve vracaju null ili empty. UserService bi trebalo da ima @autowired instancu UserRepository-ija i onda da se u metodama ove klase zovu metode repository-ja. @DusanGligorijevic Mozes to da dodas?

2023-03-08 22:08 UTC, ntadicrn4419 requested changes
Implementirati metode UserService-a

2023-03-09 10:44 UTC, andrejanesic approved these changes
Dogovorena dorada od @ntadicrn4419

2023-03-09 10:44 UTC, merged